@startuml packages_generic
set namespaceSeparator none
package "detection_rules.generic" as detection_rules.generic {
}
package "detection_rules.generic.broadcasting_feature_not_used" as detection_rules.generic.broadcasting_feature_not_used {
}
package "detection_rules.generic.columns_and_datatype_not_explicitly_set" as detection_rules.generic.columns_and_datatype_not_explicitly_set {
}
package "detection_rules.generic.deterministic_algorithm_option_not_used" as detection_rules.generic.deterministic_algorithm_option_not_used {
}
package "detection_rules.generic.empty_column_misinitialization" as detection_rules.generic.empty_column_misinitialization {
}
package "detection_rules.generic.hyperparameters_not_explicitly_set" as detection_rules.generic.hyperparameters_not_explicitly_set {
}
package "detection_rules.generic.in_place_apis_misused" as detection_rules.generic.in_place_apis_misused {
}
package "detection_rules.generic.memory_not_freed" as detection_rules.generic.memory_not_freed {
}
package "detection_rules.generic.merge_api_parameter_not_explicitly_set" as detection_rules.generic.merge_api_parameter_not_explicitly_set {
}
package "detection_rules.generic.nan_equivalence_comparison_misused" as detection_rules.generic.nan_equivalence_comparison_misused {
}
package "detection_rules.generic.unnecessary_iteration" as detection_rules.generic.unnecessary_iteration {
}
@enduml
